In [1]:
import numpy as np

### Задание_1

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание_2

In [9]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(12, 1)
a4 = a.reshape(4, 3)
a5 = a.reshape(6, 2)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]))

### Задание_3

In [16]:
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(6, -1)
a4 = a.reshape(-1, 4)
a5 = a.reshape(-1, 2)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]))

### Задание_4

In [19]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
a1 = a.reshape(2,5)
a2 = a1.reshape(10, 1)
a2

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

Одномерным назвать нельзя

### Задание_5

In [24]:
a=np.random.randn(3,4)
a

array([[-0.77647185, -0.80520632,  1.07953861,  0.43273342],
       [-0.75060322, -0.82518199, -0.73329875, -1.32381176],
       [ 1.03489612, -0.62363544,  0.2541293 ,  0.89008117]])

In [25]:
a.flatten()

array([-0.77647185, -0.80520632,  1.07953861,  0.43273342, -0.75060322,
       -0.82518199, -0.73329875, -1.32381176,  1.03489612, -0.62363544,
        0.2541293 ,  0.89008117])

### Задание_6

In [29]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание_7

In [30]:
b=np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

b - двумерный

### Задание_8

In [34]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [35]:
b = np.zeros((3, 2)) + 1
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
v.size

10

### Задание_9

In [44]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [49]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [51]:
det_B = np.linalg.det(B)
det_B

0.0

Обратной матрицы не существует, так как матрица вырожденная

### Задание_10

In [52]:
np.random.seed(42)

### Задание_11

In [54]:
c = np.random.randint(1, 16, 16)
c

array([ 4, 13, 15, 11,  8, 13,  5,  7, 10,  3,  7, 11, 11,  8,  5,  4])

### Задание_12

In [62]:
C = c.reshape(4, 4)
C

array([[ 4, 13, 15, 11],
       [ 8, 13,  5,  7],
       [10,  3,  7, 11],
       [11,  8,  5,  4]])

In [64]:
D = B + C * 10
D

array([[ 45, 144, 173, 142],
       [ 94, 180, 136, 192],
       [123, 116, 219, 322],
       [142, 202, 262, 342]])

In [65]:
D_det = np.linalg.det(D)
D_det

15670000.0

In [66]:
D_rank = np.linalg.matrix_rank(D)
D_rank

4

In [70]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.05818251, -0.06765284, -0.10788768,  0.16371666],
       [ 0.01121506,  0.0234231 ,  0.01663689, -0.03347033],
       [-0.00757626, -0.03663816, -0.03902999,  0.06046203],
       [ 0.02333759,  0.04232291,  0.06486918, -0.09160179]])

### Задание_13

In [71]:
D_inv=np.where(D_inv < 0, 0, 1)
D_inv

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 1, 0]])

In [72]:
E=np.where(D_inv==1, B, C)
E

array([[  4,  13,  15,  32],
       [ 14,  50,  86,   7],
       [ 10,   3,   7, 212],
       [ 32, 122, 212,   4]])